### PR TITLE
Don't pollute the outline- namespace

### PR DESCRIPTION
**Pull request by thblt**
This PR removes all definitions on the `outline-` pseudo-namespace from outshine.el

 - Functions and variables already defined by `outline.el` are completely removed.
 - Other functions and variables are renamed from `outline-*` to `outshine-outline-*`.

I've tested the changes, and they seem to work perfectly. 

The detail of what is renamed and removed is in each commit message.

This PR is a superset of #16.  It can completely replace it, but the changes here go beyond a simple bug fix --- they're a *complicated* bug fix, as they even fix *future* bugs :crystal_ball: :-) 

Thanks!

### CODE REVIEW

**Comment by thblt** [comment]
Missing: `outline-show-more`

[i will update this post as I find more]

**Comment by thblt** [comment]
Please ignore this for now, this breaks outshine.  I'm fixing it,  should be done soon.

**Comment by thblt** [comment]
OK, done, sorry for the noise.  I have updated the original description,

**Comment by alphapapa** [comment]
Thank you very much.  I don't have time to review this right now, but it looks good, and it needs to be done.

What about renaming the symbols by simply changing `outline` to `outshine` instead of prepending `outshine`?  `outshine-*` seems sufficient, rather than `outshine-outline-*`.  What do you think?

**Comment by thblt** [comment]
> What about renaming the symbols by simply changing outline to outshine

I don't really have an opinion on that matter, tbh.  The rationale behind the double prefix was that these are functions in outshine but which apply on `outline-[minor-]mode`, regardless of whether outshine is activated. (Also, it was easier to add than to change a prefix) 

For future reference, here's the code I used, so we can adjust it to repeat the changes with any rename strategy you'll prefer: 

``` elisp
(mapcar
 (lambda (f)
   (goto-char (point-min))
   (while (re-search-forward (format "\\<%s\\>" f) nil t)
     (replace-match (format "outshine-%s" f))))
 '(outline-body-p
   outline-body-visible-p
   outline-change-heading
   outline-change-level
   outline-cleanup-match
   outline-cycle
   outline-cycle-emulate-tab
   outline-headings-atom
   outline-headings-list
   outline-hide-more
   outline-next-line
   outline-show-more
   outline-static-level-p
   outline-subheadings-p
   outline-subheadings-visible-p))
```

(there' a bug I just noticed, because `outline-cycle-emulate-tab` matches `\<outline-cycle\>` --- `-` is a word boundary.  I `--force push`ed a fixed commit)

In a few minutes (as soon as I find back my PGP smartcard :) I'm going to push two new commits on this branch:

 - one removing `outline-mode-easy-bindings.el` entirely --- the file [is marked as obsolete](https://github.com/alphapapa/outshine/blob/master/outline-mode-easy-bindings.el#L1-L2) and does the same nasty `outline-` overrides we're removing in this PR.  
 - one to rebase on current master and fix the conflict.

**Comment by thblt** [comment]
This is mergeable again.

**Comment by alphapapa** [comment]
Thank you very much!

I'm tempted to go ahead and merge this without further question, but I did think of one: It seems like merging this could result in a change in behavior for existing users, because although this package shouldn't override these functions, it has been.  So users who upgrade to this version will suddenly have the "real" `outline` functions again, which is ultimately what we want, but they may have subtle differences in behavior.

You said you tested this PR (which I greatly appreciate!), but I'm curious: does that mean that you tested these commands and functions, which are effectively new ones now, or that you tested the `outline-` functions, which should no longer be overridden?

I'm not sure if all this matters, because this is ultimately the right thing to do.  But I do wonder if we need to do anything to smooth over any kind of transition.  What do you think?

Thanks.

**Comment by thblt** [comment]
> they may have subtle differences in behavior.

I'm not too worried about that, i suspect most of the changes will be bugfixes.  The worse that may (and will) happen is keybindings to renamed functions that will suddenly become invalid.    But it can't really be avoided.

> does that mean that you tested these commands and functions, which are effectively new ones now, or that you tested the outline- functions, which should no longer be overridden?

I tested a reasonable set of both `outshine-outline-*` and `outline-` (after `outshine-hook-function`), and everything seems to work as expected.  More generally, I've been using my branch instead of your HEAD (i manage my packages with [Borg](https://github.com/emacscollective/borg), so branch switch is a transparent operations from Emacs' PoV) since the beginning of this PR, and except for the original, overdestructive attempt, I haven't noticed any issue.  But outshine is complex, and although I'm reasonably confident nothing catastrophic should arise from these changes, I cannot guarantee there won't be some quirks along the way :)

> But I do wonder if we need to do anything to smooth over any kind of transition

IMHO, the correct thing to do is advertise the merge as soon as it's done (and before Melpa build completes), so people can be warned their next update may require some manual changes in their config.  I can draft a Reddit post, for example, the Reddit Emacs community is quite active (much more than the `emacs-tangents` mailing list anyway)

(Also, maybe just don't tag a new release before one or two weeks after the merge, so people who use melpa-stable won't receive an undertested version)

**Comment by alphapapa** [comment]
Hi,

I'm sorry I neglected this for a while.

> IMHO, the correct thing to do is advertise the merge as soon as it's done (and before Melpa build completes), so people can be warned their next update may require some manual changes in their config. I can draft a Reddit post, for example, the Reddit Emacs community is quite active (much more than the emacs-tangents mailing list anyway)

Would you be willing to have a "flag day" with a few weeks advance notice?  e.g. we could post to Reddit (and maybe the Org mailing list), with a date decided in advance, explaining the changes that will be made and when, and a link to the branch that will be merged.  Then on that day, we merge that branch to `master` and let MELPA build the new package.

That might be overkill, but this package has been around for a long time, and a lot of users have installed it, and I would like to avoid breaking anyone's config with weird errors without notice.  That happens too much on MELPA already.  Few users keep their packages in version control, which would allow them to rollback to the previous version and fix the breakage at a later time, so most people who would experience such breakage (if there is any) might be stuck with fixing it at the time.

Thanks for your work on this!

**Comment by thblt** [comment]
@alphapapa that's a good idea, I can draft an announcement, hopefully this weekend, and we could merge in something like six weeks?  I'm a bit too busy right now, so publishing the annonce somewhere in the next two weeks for a merge in mid-october would be ideal to allow me to follow up on eventual issues, if that's OK with you too?

**Comment by alphapapa** [comment]
Sure, that sounds fine.  Thank you for your work on this.

**Comment by thblt** [comment]
Later than expected, here's an announcment draft.  Tell me what you think, and don't hesitate to correct my English ;)

# Outshine users: big changes ahead, some testing needed!

[The first of two major PRs](https://github.com/alphapapa/outshine/pull/17) is about to be merged on the [Outshine](https://github.com/alphapapa/outshine/) package.  For historical reasons, Outshine used to (re)define a lot of functions and variables in the `outline-` pseudo namespace, conflicting with the built-in Outline it extends, and reintroducing long-fixed bugs in the process (because some of the `outline-*` functions it defined were actually provided by Outline, but Outshine redefined them using older definitions!).  This PR removes most of these definitions, and renames those that no other package provides.  This is the first step in making Outshine a polite citizen of modern Emacs world.

We (/u/github-alphapapa and myself) believe the changes should have absolutely no effect beyond fixing some bugs and quirks in Outshine but... it's a big refactoring, so you never know.  We thus kindly ask Outshine users to give [thblt's `leave-outshine-alone` branch](https://github.com/thblt/outshine/tree/leave-outline-alone) a try before it gets merged, and [report](https://github.com/alphapapa/outshine/issues) any issue you encounter --- try to make it reproducible if you can, but report anyway!

Merge will happen on October 20th, 2018, around 12:00 UTC, and should be picked up by Melpa the usual way, and will be tagged so that Melpa Stable picks it up as well.

Thanks!
Adam (Alphapapa) & Thibault (Thblt), co-maintainers of Outshine

------ 

PS: If you're feeling especially adventurous, you may even give a try to the *second* big PR.  This one will turn Outshine into a real minor mode, isolating its effects using the regular Emacs mechanisms, instead of the big override it currently is.  It may be a bit more tricky, but it will be merged later, not before November.  If you're interested, [begin reading here](https://github.com/alphapapa/outshine/pull/19).

**Comment by alphapapa** [comment]
Hey, that looks great!  Thanks very much for writing that up.

**Comment by thblt** [comment]
[The announcement is live!](https://www.reddit.com/r/emacs/comments/9hpkfr/outshine_users_big_changes_ahead_some_testing/)

**Comment by kaushalmodi** [comment]
A cosmetic change suggestion. 

- Would you like to refactor the non-interactive and "users should not meddle with these" functions from `outshine-foo` to `outshine--foo`?

**Comment by alphapapa** [comment]
> The announcement is live!

Wonderful, thank you!

> A cosmetic change suggestion.

I have no objection.

**Comment by yuhan0** [comment]
Speaking of naming suggestions, what about shortening the currently named `outshine-outline-*` functions and variables to simply `outshine-*`? As far as I can tell, this only serves to document which symbols used to override the outline 'namespace'.

Aside from being slightly redundant, it results in some API inconsistency, eg. between `outshine-outline-cycle` and `outshine-cycle-buffer`, or `outline-next-heading` / `outshine-next-link` / `outshine-outline-next-line`


As  a quick reference here are the mentioned symbols:
```
Functions:
(interactive)
    outshine-outline-subheadings-visible-p
    outshine-outline-cycle
    outshine-outline-hide-more
    outshine-outline-next-line
    outshine-outline-show-more

(Non-interactive)
    outshine-outline-body-visible-p
    outshine-outline-subheadings-p
    outshine-outline-change-heading
    outshine-outline-cycle-emulate-tab
    outshine-outline-headings-list
    outshine-outline-cleanup-match
    outshine-outline-change-level
    outshine-outline-body-p
    outshine-outline-headings-atom
    outshine-outline-static-level-p

Variables:
    outshine-outline-cycle-emulate-tab
    outshine-outline-promotion-headings
    outshine-outline-regexp-base
    outshine-outline-regexp-outcommented-p
    outshine-outline-regexp-special-chars
```

Thanks so much for the hard work put into this refactoring!

**Comment by yuhan0** [comment]
This update breaks compatibility with [navi-mode](https://github.com/alphapapa/navi/), which contains references to `outline-promotion-headings` and `outline-cycle`.
These were refactored to `outshine-outline-promotion headings` and `outshine-outline-cycle` respectively, and doing a simple search-and-replace inside navi-mode.el seems to have fixed it. I'm willing to submit a PR there but there could be other renamed symbols that I missed?

On another note, I agree with the above comments about how the newly renamed `outshine-outline-*` functions could be better renamed as `outshine-*`for better consistency - currently it seems rather arbitrary - e.g. with `outshine-outline-cycle` vs `outshine-cycle-buffer`, `outshine-next-link` vs `outshine-outline-next-line` ( vs original `outline-next-heading`).

**Comment by thblt** [comment]
@yuhan0 

> On another note, I agree with the above comments about how the newly renamed outshine-outline-* functions could be better renamed as outshine-*for better consistency

I opened issue #21 to track that.

**Comment by thblt** [comment]
@yuhan0  If you've made the changes could you please send a PR against whichever branch you've modified? Thanks!

**Comment by yuhan0** [comment]
Done :)

Another minor compatibility issue I just picked up - the `outorg` package has a reference to the deprecated `outshine-hook-function`, causing it to throw several warnings whenever `outorg-edit-as-org` is called.
I suppose since these packages (outshine/outorg/navi) are so integrated with each other, the fixes should be merged in some sort of synchronized manner on the 20th October date?
I'm fairly new to all this but would be glad to send simple PRs for the other two packages as well :)

**Comment by thblt** [comment]
OK, I'm late, sorry all.

I've just pushed the commit to `s/<outshine-outline/outshine-/` to my branch, but Github doesn't seem to be picking it up yet.  I haven't had a look at the compatibility issue with outorg @yuhan0 described. @yuhan0, can you confirm the issue only affects the second PR (#19), since #17 (this one) doesn't change outshine-hook-function? also yes, PRs would be really appreciated! (against outorg/master and thblt/outshine/be-a-nice-minor-mode-not-a-nasty-override). Thanks!

@alphapapa, I consider this mergable as soon as Github notices https://github.com/thblt/outshine/commit/6c3b071936a0e30f1ef12b9fb24b5f949784407c exists, I let you review the last changes before I (or you) proceed to merge!

**Comment by thblt** [comment]
It's good, all 8 commits are here!

**Comment by thblt** [comment]
OK, I'm late, sorry all.

I've just pushed the commit to `s/<outshine-outline/outshine-/` to my branch.  I haven't had a look at the compatibility issue with outorg @yuhan0 described, but I assume it only affects the second PR (#19), since #17 (this one) doesn't change outshine-hook-function. @yuhan0, can you confirm this? (Also yes, PRs would be really appreciated!  - against outorg/master and thblt/outshine/be-a-nice-minor-mode-not-a-nasty-override. Thanks!) 

@alphapapa, I think this can be merged, I let you review the last changes if you want before I (or you) proceed :)

**Comment by thblt** [comment]
OK, I'm late, sorry all.

I've just pushed the commit to `s/<outshine-outline/outshine-/` to my branch.  I haven't had a look at the compatibility issue with outorg @yuhan0 described, but I assume it only affects the second PR (#19), since #17 (this one) doesn't change outshine-hook-function. @yuhan0, can you confirm this? (Also yes, PRs would be really appreciated!  - against outorg/master and thblt/outshine/be-a-nice-minor-mode-not-a-nasty-override. Thanks!) 

@alphapapa, I think this can be merged, I let you review the last changes if you want before I (or you) proceed :)

**Comment by thblt** [comment]
Github says "You can't comment at this time". If *this* comment makes it through, it means my other, longer, actually useful comment triggered some antispam filter somewhere.

**Comment by thblt** [comment]
Github says "You can't comment at this time". If *this* comment makes it through, it means my other, longer, actually useful comment triggered some antispam filter somewhere.

**Comment by thblt** [comment]
OK, I'm late, sorry all.

I've just pushed the commit to `s/<outshine-outline/outshine-/` to my branch.  I haven't had a look at the compatibility issue with outorg @yuhan0 described, but I assume it only affects the second PR (#19), since #17 (this one) doesn't change outshine-hook-function. @yuhan0, can you confirm this? (Also yes, PRs would be really appreciated!  - against outorg/master and thblt/outshine/be-a-nice-minor-mode-not-a-nasty-override. Thanks!) 

@alphapapa, I think this can be merged, I let you review the last changes if you want before I (or you) proceed :)

**Comment by thblt** [comment]
Github says "You can't comment at this time". If *this* comment makes it through, it means my other, longer, actually useful comment triggered some antispam filter somewhere.

**Comment by thblt** [comment]
OK great, after explaining that "You can't comment at this time.", Github is publishing every message it initially rejected.  Sorry for the noise.

**Comment by yuhan0** [comment]
Hi @thblt, your comments are coming through the email notifications regularly, but not on this comments page - It appears that github servers are having some issues right now: https://status.github.com/messages

Let's wait for it to get resolved before continuing the discussion :)

**Comment by thblt** [comment]
I'm late, sorry all.

I've just pushed a commit to `s/<outshine-outline/outshine-/`, which should be the very last part of this PR.  I haven't had a look at the compatibility issue with outorg @yuhan0 described, but I assume it only affects the second PR (#19), since #17 (this one) doesn't change outshine-hook-function. @yuhan0, can you confirm this? (Also yes, PRs would be really appreciated!  - against outorg/master and thblt/outshine/be-a-nice-minor-mode-not-a-nasty-override. Thanks!)

@alphapapa, I think this can be merged, I let you review the last changes if you want before I (or you) proceed :)

**Comment by alphapapa** [comment]
@thblt I'm not at a computer right now, so I'll let you merge to master
when you are ready.  I'll look at it later, but I'm sure you've done a good
job.   Thanks for all your work on this.

**Comment by thblt** [comment]
Merged + created and tagged version `v2.1` for Melpa stable.

**Comment by yuhan0** [comment]
Oops, this might be a little late, but I just noticed that `outline-promote` and `outline-demote` were deleted in commit fdf8b204ed4c9be50eec10bbd6f2561f93f9a0b8 and they depend on the  `outshine-change-level` helper function which has no other references. 

Found this while trying to configure the outshine variables for markdown mode, and not being able to get promoting/demoting to work. I haven't really investigated what added functionality those deleted functions provide, and so far the regular outline-mode functions have worked fine for me, mostly in elisp and python modes.

Should they be restored and renamed to `outshine-promote` and `outshine-demote`, 
or have `outshine-change-level` removed?

**Comment by thblt** [comment]
@yuhan0  On my Emacs, these functions are provided by `outline.el`. Is this not the case for you?

**Comment by thblt** [comment]
Also I'm not sure Outshine can work with Markdown since AFAIK it requires that the major mode supports comments. But I may be wrong, in which case I'd be interested to see your config.

**Comment by yuhan0** [comment]
> @yuhan0 On my Emacs, these functions are provided by `outline.el`. Is this not the case for you?

Yes, sorry if I didn't make it clear - I was pointing out that `outshine-change-level` was being referenced _only_ by the promote and demote functions in the previous version of outshine, and that either it should be removed too or to investigate if there was a good reason for outshine to override `outline-promote/demote` functions in the first place.

**Pull request merged**
