### PR TITLE
Standardize indentation

### PR DESCRIPTION
**Pull request by yuhan0**
I went ahead and indented the outshine-org-cmds.el file as well - this PR is entirely whitespace and indentation changes.

### CODE REVIEW

**Comment by yuhan0** [comment]
Sorry, just realised I hadn't rebased onto the latest master - give me a few minutes to sort out the conflicts

**Comment by thblt** [comment]
@yuhan0 Notice @alphapapa  implemented some of these changes a few minutes ago (but only part of them though, there's still a point in rebasing).

@alphapapa Can you hold the changes on master for just a few minutes while we merge this?

**Comment by yuhan0** [comment]
Oh, I didn't notice the changes were so recent. 
@alphapapa if you'd prefer to fix the indentation yourself that's fine with me too! 
It was just a call to indent-region with indent-tabs-mode set to nil

**Comment by thblt** [comment]
@yuhan0  It seems there's a lot of small changes going on, maybe global cosmetic changes can wait.  Can you resend the outshine-cycle PR so we can start checking it?   IIRC it's reasonably self contained, so it will be easy to work on even while other things are going on.

**Comment by alphapapa** [comment]
@thblt Unfortunately I wasn't looking at GitHub while making the tidy commits.  Maybe we should have a chat room or something to do live coordination.  :)  Sorry for any confusion.

I'm done for now, so go ahead with whatever you like.  Thanks for your work.

**Comment by yuhan0** [comment]
Well, I was kinda hoping to minimize the merge conflicts from global cosmetic tweaks on a 4000-line file overlapping with the 2 months worth of commits here on my local branch - guess that's unavoidable now.. Might be a good time to learn my way around ediff and magit's merging tools!
Happy new year to everyone 🎉  I'll close this PR

**Comment by alphapapa** [comment]
@yuhan0 You may find this helpful in resolving merge conflicts, it's much faster and easier than ediff for me: https://github.com/alphapapa/unpackaged.el#hydra

**Pull request closed without merging**
