### PR TITLE
Unleash partly missing fontification

### PR DESCRIPTION
**Pull request by brandm**

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi, thanks.  Would you please explain the purpose and background of this PR?

**Comment by brandm** [comment]
Sure.

For some Emacs Lisp files I observed that no outshine headings or in other cases only those in the second half of the file are fontified. See for example the Emacs Lisp files in commit e036123 of http://github.com/brandm/emacs.d after turning off `orgstruct-mode`. This change resolves the issue for me.

**Comment by alphapapa** [comment]
I see.  I've never noticed this problem myself.  Are you sure that isn't caused by `orgstruct-mode`?  I think having both it and outshine enabled at the same time would be expected to cause conflicts.  Also note that `orgstruct-mode` is likely to be deprecated or removed from Org soon because of the relatively poor state of its code; see recent discussion on the mailing list.

**Comment by brandm** [comment]
> Are you sure that isn't caused by orgstruct-mode? I think having both it and outshine enabled at the same time would be expected to cause conflicts.

Even when I restart Emacs and never use `orgstruct-mode` by removing the file local variable `eval: (orgstruct-mode)` the issue disappears only in the mentioned Emacs Lisp files but not in this minimal working example:

```
#!/bin/sh
# * a
```

> Also note that orgstruct-mode is likely to be deprecated or removed from Org soon because of the relatively poor state of its code; see recent discussion on the mailing list.

See my GitHub full name to see that I am part of this discussion. The removal is why I have made these two PRs.

**Comment by alphapapa** [comment]
Great, I verified the ECM as you said, and the PR seems to fix it.  Thanks for fixing this.

> See my GitHub full name to see that I am part of this discussion. The removal is why I have made these two PRs.

Oh, hi.  :)

**Pull request merged**
