### PR TITLE
Various improvements to outshine-cycle

### LINKED ISSUE #26: Obsolete function and wrong number of arguments warnings
When byte-compiling outshine, Emacs prints these warnings:
```
In outshine-set-hidden-lines-cookie: outshine.el:1220:8:Warning: ‘show-entry’
is an obsolete function (as of 25.1); use ‘outline-show-entry’ instead.
outshine.el:1231:8:Warning: ‘hide-entry’ is an obsolete function (as of 25.1);
use ‘outline-hide-entry’ instead.

In outshine-cycle: outshine.el:1941:16:Warning: ‘show-branches’ is an obsolete
function (as of 25.1); use ‘outline-show-branches’ instead.
outshine.el:1950:10:Warning: ‘show-all’ is an obsolete function (as of 25.1);
use ‘outline-show-all’ instead.
outshine.el:1968:12:Warning: ‘hide-sublevels’ is an obsolete function (as of
25.1); use ‘outline-hide-sublevels’ instead.
outshine.el:1993:12:Warning: ‘show-entry’ is an obsolete function (as of
25.1); use ‘outline-show-entry’ instead.
outshine.el:1994:12:Warning: ‘show-children’ is an obsolete function (as of
25.1); use ‘outline-show-children’ instead.
outshine.el:2002:12:Warning: ‘show-subtree’ is an obsolete function (as of
25.1); use ‘outline-show-subtree’ instead.
outshine.el:2007:12:Warning: ‘hide-subtree’ is an obsolete function (as of
25.1); use ‘outline-hide-subtree’ instead.

In outshine-hide-more: outshine.el:2078:13:Warning: ‘hide-entry’ is an
obsolete function (as of 25.1); use ‘outline-hide-entry’ instead.
outshine.el:2079:13:Warning: ‘hide-leaves’ is an obsolete function (as of
25.1); use ‘outline-hide-leaves’ instead.
outshine.el:2081:13:Warning: ‘hide-subtree’ is an obsolete function (as of
25.1); use ‘outline-hide-subtree’ instead.

In outshine-show-more: outshine.el:2088:13:Warning: ‘show-children’ is an
obsolete function (as of 25.1); use ‘outline-show-children’ instead.
outshine.el:2096:13:Warning: ‘show-subtree’ is an obsolete function (as of
25.1); use ‘outline-show-subtree’ instead.
outshine.el:2094:13:Warning: ‘show-entry’ is an obsolete function (as of
25.1); use ‘outline-show-entry’ instead.
outshine.el:2095:12:Warning: ‘show-subtree’ is an obsolete function (as of
25.1); use ‘outline-show-subtree’ instead.

In outshine-hide-hidden-lines-cookies: outshine.el:2123:8:Warning: ‘show-all’
is an obsolete function (as of 25.1); use ‘outline-show-all’ instead.

In outshine-toggle-subtree-comment-status: outshine.el:2186:8:Warning:
looking-back called with 1 argument, but requires 2-3
outshine.el:2197:14:Warning: looking-back called with 1 argument, but requires
2-3
outshine.el:2197:14:Warning: looking-back called with 1 argument, but requires
2-3
outshine.el:2197:7:Warning: looking-back called with 1 argument, but requires
2-3

In outshine-agenda-create-temporary-agenda-file:
outshine-org-cmds.el:78:36:Warning: reference to free variable
‘outshine-temporary-directory’

In outshine-agenda: outshine-org-cmds.el:303:27:Warning: reference to free
variable ‘outshine-temporary-directory’

In outshine-time-stamp: outshine-org-cmds.el:4336:16:Warning:
‘org-on-heading-p’ is an obsolete function (as of Org 9.0); use
‘org-at-heading-p’ instead.

In outshine-time-stamp-inactive: outshine-org-cmds.el:4363:16:Warning:
‘org-on-heading-p’ is an obsolete function (as of Org 9.0); use
‘org-at-heading-p’ instead.
```

### PR DESCRIPTION
**Pull request by yuhan0**
As requested the changes have been split into multiple commits :)

- Prevent cycling messages from being logged to messages buffer
- Resolve obsolete function warnings when byte compiling ( Closes #26 )
- Refactor global cycling behavior into outshine-cycle-buffer function
- Add numeric prefix argument to outshine-cycle-buffer
- Dispatch to org-cycle and org-cycle-buffer when called from org-mode
- Implement 2-state cycling for headings without children subheadings ( Closes tj64#29 )

### CODE REVIEW

**Comment by yuhan0** [comment]
Alright sorry, I wasn't aware of such requirements in advance. I'll have to send them in one at a time because most of the commits here depend on the preceding ones.

Just curious, did you look at the refined diff for 4f52cc0a61038be187869000e486c7d23c44814f? It's a relatively minor change but shows up as many lines because of indentation changes.

**Comment by alphapapa** [comment]
> Just curious, did you look at the refined diff for 4f52cc0? It's a relatively minor change but shows up as many lines because of indentation changes.

No, I didn't.  Please make indentation changes in separate commits so that the changes can be reviewed efficiently.

FYI, I use `aggressive-indent-mode` when editing elisp files, which ensures indentation is always correct.  You should probably use it when working on this project, as it will ensure that there are no stray indentation changes that make diffs more confusing.

**Comment by yuhan0** [comment]
Yup I use aggressive-indent as well, that diff in particular was well indented and involved raising a large nested cond form which caused all its child forms to change indentation.

**Comment by alphapapa** [comment]
Ok, thanks, I'll look forward to seeing that commit's PR.  :)

**Pull request closed without merging**
